version: '2.4'
services:
  # Postgres database
  postgres:
    build: ./postgres
    ports:
      - 5432:5432
    tty: true
    stdin_open: true
    platform: linux
  # DSpace
  dspace-dev:
    build:
        context: .
        target: base
    ports:
      - 8080:8080
      - 8000:8000
      #Remote Debugger
      - 1043:1043
    depends_on:
      - postgres
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      # Path on the host, relative to the Compose file
      #- type: bind
      #  #source: c:/Users/ko_ok/sources/dspace-dev-docker/dspace-build
      #  source: ./dspace-build
      #  target: /srv/dspace
      - type: bind
        #source: c:/Users/ko_ok/sources/viadat-repo
        source: /c/Users/ko_ok/sources/viadat-repo
        target: /srv/dspace-src
        # - type: bind
        # - #source: c:/Users/ko_ok/.m2
        # - source: /c/Users/ko_ok/.m2
        # - target: /home/developer/.m2
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: /bin/bash
    tty: true
    stdin_open: true
    platform: linux
